version: '3'
services:
  psql:
    image: postgres:15.3
    container_name: booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5436:5432'